Repository cse110-sp24-group3/cse110-sp24-group3, pull requests merged in 2024-06, with the labels that each got.

#72 Three Dots Entry Page
  application/web/assets/checkmark.svg
  application/web/assets/devmode-icon.svg
  application/web/assets/markdown-icon.svg
  application/web/assets/trashcan-red.svg
  application/web/assets/vdots-grey-active.svg
  application/web/assets/vdots-grey.svg
  application/web/index.html
  application/web/main.css
  application/web/scripts/dropdown.js
Labels: enhancement, Sprint 2, M

#94 Refactor web js
  application/eslint.config.mjs
  application/main.js
  application/web/JournalAPI.js
  application/web/index.html
  application/web/main.css
  application/web/scripts/homepage/homepage.js
  application/web/scripts/sidebar/sidebar.js
  application/web/style/entry.css
  application/web/style/global-variables.css
  application/web/style/header.css
  application/web/style/homepage.css
  application/web/style/sidebar.css
  application/web/style/top-level.css
  application/web/web.js
  docs/Entry.html
  docs/Journal.html
  docs/JournalAPI.html
  docs/JournalAPI.js.html
  docs/global.html
  docs/index.html
  docs/scripts_homepage_homepage.js.html
  docs/scripts_sidebar_sidebar.js.html
Labels: XL

#98 feat: added app packaging
  .gitignore
  application/eslint.config.mjs
  application/instone-rock.icns
  application/main.js
  application/package-lock.json
  application/package.json
  application/preload.js
  application/preload.test.js
Labels: Sprint 3

#113 chore: cleaned up bad selectors in sidebar.js
  application/web/index.html
  application/web/scripts/sidebar/sidebar.js
  application/web/style/sidebar.css
  application/web/web.js
Labels: bug

#114 Created E2E Tests for the Sidebar component using Microsoft Playwright
  .gitignore
  admin/specs/adrs/060624-Decision-Playwright.md
  application/jest-puppeteer.config.js
  application/main.js
  application/package-lock.json
  application/package.json
  application/tests/e2e/sidebar.test.js
  application/tests/unit/preload.test.js
  application/web/scripts/sidebar/sidebar.js
Labels: Sprint 3

#104 #49 New Journal Button allows user to title new journals
  .gitignore
  application/main.js
  application/mock/.gitkeep
  application/package-lock.json
  application/package.json
  application/preload.js
  application/tests/e2e/homepage.test.js
  application/web/JournalAPI.js
  application/web/index.html
  application/web/scripts/homepage/homepage.js
  application/web/scripts/sidebar/sidebar.js
  application/web/style/sidebar.css
  docs/Entry.html
  docs/Journal.html
  docs/JournalAPI.html
  docs/JournalAPI.js.html
  docs/global.html
  docs/index.html
  docs/scripts_homepage_homepage.js.html
  docs/scripts_sidebar_sidebar.js.html
Labels: enhancement, XL

#122 fix: fixed errors from merge
  application/main.js
  application/web/scripts/homepage/homepage.js
Labels: bug

#124 [FEAT] Added feature to load journals from storage and edit existing entries
  application/web/index.html
  application/web/scripts/homepage/homepage.js
  application/web/scripts/sidebar/sidebar.js
Labels: enhancement

#130 fix: electron windows compatability
  application/package-lock.json
  application/package.json
Labels: bug, Sprint 3, S

#131 Delete journals
  application/main.js
  application/web/index.html
  application/web/scripts/homepage/homepage.js
  application/web/scripts/sidebar/sidebar-dropdown.js
  application/web/scripts/sidebar/sidebar.js
  application/web/web.js
Labels: enhancement, Sprint 3, M

#140 feat: added delete entry functionality to editing entry page
  application/web/index.html
  application/web/scripts/editing-entry/editing-entry-dropdown.js
  application/web/scripts/editing-entry/entry-title-script.js
  application/web/scripts/homepage/homepage.js
  application/web/scripts/sidebar/sidebar.js
  application/web/style/entry.css
Labels: Sprint 3, M
