Repository cse110-sp24-group3/cse110-sp24-group3, pull requests merged in 2024-05, with the labels that each got.

#29 fix: hotfix for sidebar view
  application/web/index.html
  application/web/main.css
Labels: bug

#30 9 Sidebar Wrapper HTML
  application/web/assets/journal-icon.png
  application/web/index.html
  application/web/main.css
Labels: Sprint 1

#37 BREAKING CHANGE: implemented linting for HTML & provided additional CSS
  application/web/assets/drawer.svg
  application/web/assets/instone-rock.svg
  application/web/assets/journal-icon.png
  application/web/assets/journal-icon.svg
  application/web/assets/vdots.svg
  application/web/index.html
  application/web/main.css
Labels: bug

#39 Added sidebar collapse button and functionality
  application/web/index.html
  application/web/main.css
  application/web/web.js
Labels: Sprint 1

#44 chore: remove Font Awesome CDN
  application/web/index.html
  application/web/main.css
Labels: enhancement

#61 feat: completed backend API for journals
  .gitignore
  admin/specs/backend/backend.drawio.png
  application/main.js
  application/mock/.gitkeep
  application/package-lock.json
  application/package.json
  application/preload.js
  application/web/JournalAPI.js
  application/web/index.html
  docs/Entry.html
  docs/Journal.html
  docs/JournalAPI.html
  docs/JournalAPI.js.html
  docs/fonts/OpenSans-Bold-webfont.eot
  docs/fonts/OpenSans-Bold-webfont.svg
  docs/fonts/OpenSans-Bold-webfont.woff
  docs/fonts/OpenSans-BoldItalic-webfont.eot
  docs/fonts/OpenSans-BoldItalic-webfont.svg
  docs/fonts/OpenSans-BoldItalic-webfont.woff
  docs/fonts/OpenSans-Italic-webfont.eot
  docs/fonts/OpenSans-Italic-webfont.svg
  docs/fonts/OpenSans-Italic-webfont.woff
  docs/fonts/OpenSans-Light-webfont.eot
  docs/fonts/OpenSans-Light-webfont.svg
  docs/fonts/OpenSans-Light-webfont.woff
  docs/fonts/OpenSans-LightItalic-webfont.eot
  docs/fonts/OpenSans-LightItalic-webfont.svg
  docs/fonts/OpenSans-LightItalic-webfont.woff
  docs/fonts/OpenSans-Regular-webfont.eot
  docs/fonts/OpenSans-Regular-webfont.svg
  docs/fonts/OpenSans-Regular-webfont.woff
  docs/index.html
  docs/scripts/linenumber.js
  docs/scripts/prettify/Apache-License-2.0.txt
  docs/scripts/prettify/lang-css.js
  docs/scripts/prettify/prettify.js
  docs/styles/jsdoc-default.css
  docs/styles/prettify-jsdoc.css
  docs/styles/prettify-tomorrow.css
Labels: Sprint 2

#83 fix: fixed the issue with the title prompt text 'Untitled' disappearing
  application/web/web.js
Labels: bug
